name: flutter_greenpoint
description: "GreenPoint - แอปสะสมแต้มเพื่อรณรงค์ลดการใช้พลาสติก"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  http: ^1.1.2
  flutter_dotenv: ^5.1.0
  intl: ^0.19.0
  flutter_animate: ^4.5.0
  lottie: ^3.0.0
  google_fonts: ^6.1.0
  fl_chart: ^0.66.2
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.6
  image_picker: ^1.0.7
  path_provider: ^2.1.1
  geolocator: ^10.1.0
  permission_handler: ^11.2.0
  url_launcher: ^6.2.2
  share_plus: ^7.2.2
  crypto: ^3.0.3
  local_auth: ^2.1.7
  
  # Google Sign-In (standalone)
  google_sign_in: ^6.2.1
  
  # Email Service
  mailer: ^6.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/animations/
    - .env
  
flutter_intl:
  enabled: true
  class_name: S
  main_locale: th
  arb_dir: lib/l10n
  output_dir: lib/generated
