import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LocalizationService {
  static const String _languageKey = 'selected_language';
  
  static const Map<String, Map<String, String>> _localizedValues = {
    'th': {
      'app_name': 'GreenPoint',
      'home': 'หน้าหลัก',
      'profile': 'โปรไฟล์',
      'settings': 'ตั้งค่า',
      'partner_store': 'ร้านค้าพาร์ทเนอร์',
      'rewards': 'ของรางวัล',
      'scan_qr': 'สแกน QR',
      'hello': 'สวัสดี',
      'points': 'แต้ม',
      'level': 'เลเวล',
      'logout': 'ออกจากระบบ',
      'login': 'เข้าสู่ระบบ',
      'register': 'สมัครสมาชิก',
      'email': 'อีเมล',
      'password': 'รหัสผ่าน',
      'name': 'ชื่อ',
      'notifications': 'การแจ้งเตือน',
      'language': 'ภาษา',
      'security': 'ความปลอดภัย',
      'help': 'ช่วยเหลือ',
      'about': 'เกี่ยวกับแอป',
      'change_profile_picture': 'เปลี่ยนรูปโปรไฟล์',
      'take_photo': 'ถ่ายรูป',
      'choose_from_gallery': 'เลือกจากแกลเลอรี่',
      'save': 'บันทึก',
      'cancel': 'ยกเลิก',
      'confirm': 'ยืนยัน',
      'success': 'สำเร็จ',
      'error': 'ข้อผิดพลาด',
      'loading': 'กำลังโหลด...',
      'achievements': 'ความสำเร็จ',
      'recent_activity': 'กิจกรรมล่าสุด',
      'total_points': 'แต้มรวม',
      'plastic_reduced': 'พลาสติกที่ลด',
      'days_joined': 'วันที่เข้าร่วม',
      'enable_notifications': 'เปิดการแจ้งเตือน',
      'push_notifications': 'การแจ้งเตือนแบบ Push',
      'email_notifications': 'การแจ้งเตือนทางอีเมล',
      'biometric_login': 'เข้าสู่ระบบด้วยลายนิ้วมือ',
      'change_password': 'เปลี่ยนรหัสผ่าน',
      'two_factor_auth': 'การยืนยันตัวตน 2 ขั้นตอน',
      'privacy_policy': 'นโยบายความเป็นส่วนตัว',
      'terms_of_service': 'ข้อกำหนดการใช้งาน',
      'app_version': 'เวอร์ชันแอป',
      'contact_support': 'ติดต่อฝ่ายสนับสนุน',
      'rate_app': 'ให้คะแนนแอป',
      'share_app': 'แชร์แอป',
      'preferences': 'ค่าตั้งทั่วไป',
      'support': 'การสนับสนุน',
      'legal': 'ข้อกฎหมาย',
      'danger_zone': 'โซนอันตราย',
      'reset_settings': 'รีเซ็ตการตั้งค่า',
      'reset_all_settings': 'รีเซ็ตการตั้งค่าทั้งหมด',
      'sign_out_account': 'ออกจากบัญชี',
      'enabled': 'เปิด',
      'disabled': 'ปิด',
      'manage_security': 'จัดการความปลอดภัย',
      'faq_support': 'คำถามที่พบบ่อยและการสนับสนุน',
      'app_info': 'ข้อมูลแอป',
      'rate_on_store': 'ให้คะแนนในสโตร์',
      'share_with_friends': 'แชร์กับเพื่อน',
      'view_privacy': 'ดูนโยบายความเป็นส่วนตัว',
      'view_terms': 'ดูข้อกำหนดการใช้งาน',
      'logout_confirmation': 'คุณต้องการออกจากระบบหรือไม่?',
      'biometric_enabled': 'เปิดการเข้าสู่ระบบด้วยลายนิ้วมือ',
      'biometric_disabled': 'ปิดการเข้าสู่ระบบด้วยลายนิ้วมือ',
      'biometric_error': 'เกิดข้อผิดพลาดในการตั้งค่าลายนิ้วมือ',
      'select_language': 'เลือกภาษา',
      'language_description': 'เลือกภาษาที่คุณต้องการใช้งาน',
      'available_languages': 'ภาษาที่รองรับ',
      'language_restart_note': 'การเปลี่ยนภาษาจะมีผลทันที',
      'changing_language': 'กำลังเปลี่ยนภาษา...',
      'language_changed': 'เปลี่ยนภาษาสำเร็จ',
      'restart_app': 'กรุณาปิดแอปและเปิดใหม่อีกครั้ง',
      'restart': 'เริ่มต้นใหม่',
    },
    'en': {
      'app_name': 'GreenPoint',
      'home': 'Home',
      'profile': 'Profile',
      'settings': 'Settings',
      'partner_store': 'Partner Store',
      'rewards': 'Rewards',
      'scan_qr': 'Scan QR',
      'hello': 'Hello',
      'points': 'Points',
      'level': 'Level',
      'logout': 'Logout',
      'login': 'Login',
      'register': 'Register',
      'email': 'Email',
      'password': 'Password',
      'name': 'Name',
      'notifications': 'Notifications',
      'language': 'Language',
      'security': 'Security',
      'help': 'Help',
      'about': 'About',
      'change_profile_picture': 'Change Profile Picture',
      'take_photo': 'Take Photo',
      'choose_from_gallery': 'Choose from Gallery',
      'save': 'Save',
      'cancel': 'Cancel',
      'confirm': 'Confirm',
      'success': 'Success',
      'error': 'Error',
      'loading': 'Loading...',
      'achievements': 'Achievements',
      'recent_activity': 'Recent Activity',
      'total_points': 'Total Points',
      'plastic_reduced': 'Plastic Reduced',
      'days_joined': 'Days Joined',
      'enable_notifications': 'Enable Notifications',
      'push_notifications': 'Push Notifications',
      'email_notifications': 'Email Notifications',
      'biometric_login': 'Biometric Login',
      'change_password': 'Change Password',
      'two_factor_auth': 'Two-Factor Authentication',
      'privacy_policy': 'Privacy Policy',
      'terms_of_service': 'Terms of Service',
      'app_version': 'App Version',
      'contact_support': 'Contact Support',
      'rate_app': 'Rate App',
      'share_app': 'Share App',
      'preferences': 'Preferences',
      'support': 'Support',
      'legal': 'Legal',
      'danger_zone': 'Danger Zone',
      'reset_settings': 'Reset Settings',
      'reset_all_settings': 'Reset all settings',
      'sign_out_account': 'Sign out of account',
      'enabled': 'Enabled',
      'disabled': 'Disabled',
      'manage_security': 'Manage security',
      'faq_support': 'FAQ and support',
      'app_info': 'App information',
      'rate_on_store': 'Rate on store',
      'share_with_friends': 'Share with friends',
      'view_privacy': 'View privacy policy',
      'view_terms': 'View terms of service',
      'logout_confirmation': 'Do you want to logout?',
      'biometric_enabled': 'Biometric login enabled',
      'biometric_disabled': 'Biometric login disabled',
      'biometric_error': 'Error setting up biometric authentication',
      'select_language': 'Select Language',
      'language_description': 'Choose your preferred language',
      'available_languages': 'Available Languages',
      'language_restart_note': 'Language change will take effect immediately',
      'changing_language': 'Changing language...',
      'language_changed': 'Language changed successfully',
      'restart_app': 'Please close and reopen the app',
      'restart': 'Restart',
    },
  };

  static String translate(String key, String languageCode) {
    return _localizedValues[languageCode]?[key] ?? key;
  }

  static Future<String> getLanguage() async {
    final prefs = await SharedPreferences.getInstance();
    return prefs.getString(_languageKey) ?? 'th';
  }

  static Future<void> setLanguage(String languageCode) async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_languageKey, languageCode);
  }

  static List<Map<String, String>> getSupportedLanguages() {
    return [
      {'code': 'th', 'name': 'ไทย', 'flag': '🇹🇭'},
      {'code': 'en', 'name': 'English', 'flag': '🇺🇸'},
    ];
  }
}